services:
  - type: web
    name: poker-game
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: REDIS_URL
        sync: false
